apiVersion: v1
kind: Pod
metadata:
  name: jsl
spec:
  containers:
  - name: jsl
    image: nginx
    volumeMounts:
    - name: jslvol
      mountPath: /config
      readOnly: true
  volumes:
  - name: jslvol
    configMap:
      name: jsl
