kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gce-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gce-provision
