apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec: 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/mypvc
    type: ""
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
