apiVersion: v1
kind: Pod
metadata:
  name: apptwo
  labels:
    app: apptwo
spec:
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
  containers:
    - name: apptwo
      image: kammana/apptwo:v1
      ports:
        - containerPort: 8080
