# Specify a service account name for your application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-engineering-app
  namespace: data-engineering
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-engineering-app
  namespace: data-engineering
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: data-engineering-app
    spec:
      serviceAccountName: data-engineering-app
      containers:
      - name: data-engineering-app
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: AWS_REGION
          value: “us-west-2”
        - name: WHATS_THIS_EVEN_NEED_CONFIGS_FOR
          valueFrom:
            configMapKeyRef:
              name: data-engineering-app
              key: totally.real.configs
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
          limits:
            cpu: 10m
            memory: 40Mi
