apiVersion: v1
kind: Pod
metadata:
  name: buggypod
spec:
  containers:
  - name: container
    image: ubuntu
    command: [ "bash" ]
    volumeMounts:
    - mountPath: /tmp
      name: podpvc
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  volumes:
  - name: podpvc
    persistentVolumeClaim:
      claimName: kubepvc
