apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubepv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: testvolume
  hostPath:
    path: "/pvdata"
