apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubepvc
spec:
  storageClassName: testvolume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Block
