apiVersion: v1
kind: Pod
metadata:
  name: prod-db-client-pod
  labels:
    name: prod-db-client
spec:
  serviceAccountName: prod-db-client
  containers:
  - name: db-client-container
    image: nginx
