---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: asvignesh
  name: _PVC_
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2-retain
  volumeMode: Filesystem
  volumeName: _PV_
