apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-tenant-log-minio-tenant-log-0
  labels:
      keylabel: valuelabel
spec:
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volume/nginx"
