apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "minio-tenant-log-minio-tenant-log-0"
