apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: /etc/foo
      readOnly: true
    - name: bar
      mountPath: /etc/ssl/certs/ca-bundle.crt
      subPath: ca-bundle.crt
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
