apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: myapps
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: nginx
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      volumeMounts:
        - name: my-volume
          mountPath: /app/config/app-config
          subPath: app-config
  volumes:
    - name: my-volume
      configMap:
        name: my-configmap
