apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: develop
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello
