apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx
  externalIPs:
    - 34.100.22.1
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31500
