apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rsa1
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - delete
