kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: accounts
  name: accounts-allow
spec:
  podSelector:
    matchLabels:
      app: Srv1
      Tier: backend
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          usage: finance
    ports:
      - port: 3111
