apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null  
  labels:
    rbac.authorization.k8s.io/aggregate-to-monitoring: "true"
  name: mon-endpoints
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - list
  - update
