apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app : nginx
spec:
  containers:
  - name: nginx-container
    image: registry.cloudyuga.guru/library/nginx
    ports:
    - containerPort: 80
