apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0abf84c9c65ca9456
    fsType: ext4
