apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    why_use_this_demo: "It's to learn about annotations"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  selector:
    env: prod
