apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    tier: web
    name: nginx-app
spec:
  template:
    metadata:
      name: pod-nginx
      labels:
        name: nginx-app
        tier: web
    spec:
      containers:
        - name: nginximage
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      tier: web
---
