apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  labels:
    app: react-ui
    env: prod
spec:
  selector:
    matchLabels:
      app: react-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: react-ui
        env: prod
    spec:
      containers:
        - name: react-ui
          image: deekshithsn/ui
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              memory: 2Gi
              cpu: 1
