apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jhooq-pvc-example
spec:
  volumeName: jhooq-demo-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
