apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: FOO_ENV
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: foo
