apiVersion: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations:
    kubernetes.io/service-account.name: build-robot                                 # SERVICEACCOUNT_NAME
type: kubernetes.io/service-account-token
