apiVersion: v1
kind: Secret
metadata:
  name: default-token
  annotations:
    kubernetes.io/service-account.name: default                             # SERVICEACCOUNT_NAME
type: kubernetes.io/service-account-token
