apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx-container
      image: registry.cloudyuga.guru/library/nginx
      volumeMounts:
      - name: config-volume
        mountPath: /tmp/config/nginx.conf
        subPath: nginx.conf
      - name: config-volume
        mountPath: /mnt/virtualhost.conf
        subPath: virtualhost.conf  
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
