---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx
              topologyKey: zone
      containers:
        - image: nginx:latest
          name: nginx
          volumeMounts:
            - name: vol-nginx
              mountPath: /mnt/
      volumes:
        - name: vol-nginx
          persistentVolumeClaim:
            claimName: pvc-nginx
