apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-app-volume
  labels:
    type: local
spec:
  storageClassName: manual-my-app
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/my-user/my-app/data"
