apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-definition
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 40
      containers:
      - name: front-end
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
