kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-hostpath
roleRef:
  kind: Role
  name: authorize-hostpath
  apiGroup: rbac.authorization.k8s.io
subjects:

# Authorize all service accounts in a namespace:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
