apiVersion: v1 
kind: Service 
metadata: 
  annotations: 
    tsm.tanzu.vmware.com/endpoints.statefulset: '{"app.kubernetes.io/component":"kafka","app.kubernetes.io/instance":"kafka","app.kubernetes.io/name":"kafka"}' 
  name: kafka-headless 
spec: 
  clusterIP: None 
  ports: 
  - name: tcp-client 
    port: 9092 
    protocol: TCP 
    targetPort: kafka-client 
  - name: tcp-internal 
    port: 9093 
    protocol: TCP 
    targetPort: kafka-internal
