apiVersion: v1
kind: Service
metadata:
  name: nodewebapp
spec:
  type: LoadBalancer
  selector:
    app: nodewebapp
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 8080
