apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-db
spec:
  selector:
    matchLabels:
      app: accounting-db
  template:
    metadata:
      labels:
        app: accounting-db
    spec:
      containers:
      - image: jawadhasanshani/accountingbookdb:v2
        name: accounting-db-ctr
        env:
        - name: POSTGRES_PASSWORD
          value: sasa
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata-volume
      volumes:
      - name: pgdata-volume
        emptyDir: {}
