apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: busybox
    name: test-container
    volumeMounts:
    - mountPath: /mnt/data/dataset1
      name: volume1
      subPath: dataset1
  volumes:
  - name: volume1
    emptyDir: {}
