apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:  
  containers:
  - image: nginx
    name: mypod
    volumeMounts:
    - name: myvol
      mountPath: /mnt/myvol
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: myclaim
