# The only difference is that going to cancel the service selector.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-deployment
spec:
  selector:
    matchLabels:
      app: training
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: training
        version: v1
    spec:
      containers:
      - name: training-container
        image: training:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: training-service
spec:
  type: ClusterIP
  ports:
    - name: training-port
      port: 8080
      targetPort: 80
