--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    env: test
  name: nginx
spec: 
  containers: 
    - image: nginx
      name: nginx
  nodeSelector: 
    env: prod                                                       # Node label (KEY: VALUE)
