apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  annotations:
    kubernetes.io/service-account.name: "sa-name"
# the 'kubernetes.io/service-account.name' annotation is set to an existing service account name, creating both the ServiceAccount and the Secret objects then should create the ServiceAccount object first
type: kubernetes.io/service-account-token
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  extra: YmFyCg==
