apiVersion: v1
kind: Pod
metadata:
  name: redis-cloud
spec:
  volumes:
    - name: cloud-storage
      persistentVolumeClaim:
        claimName: <NAME OF CLAIM YOU MADE EARLIER>
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: cloud-storage
          mountPath: /cloud/data
