apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ops-view
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-ops-view
    spec:
      containers:
      - name: kube-ops-view
        image: hjacobs/kube-ops-view:latest
        env:
        - name: CLUSTER_REGISTRY_URL
          value: "https://cluster-registry.example.org"
        - name: CREDENTIALS_DIR
          value: "/meta/credentials"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: credentials
          mountPath: /meta/credentials
          readOnly: true
      volumes:
      - name: credentials
        secret:
          secretName: kube-ops-view-credentials
