apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontapp
  namespace: default
spec:
  minReadySeconds: 30
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: ["web", "frontend"]
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 80
