apiVersion: v1
kind: PersistentVolume
metadata:
  name: cc-pv-volume
  labels:
    type: local
    author: ccuser
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
 # persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /docker_volume/
    server: 111.22.333.444
    readOnly: false
