apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: billing-dept-ns-privileged-psp-users
  namespace: billing-dept-ns
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: privileged-psp-user
subjects:
- kind: Group
  name: system:serviceaccounts:kube-system
  apiGroup: rbac.authorization.k8s.io
