apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dave-privileged-psp-users
  namespace: billing-dept-ns
subjects:
- kind: ServiceAccount
  name: dave-user
  namespace: kube-system
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: privileged-psp-user
