---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        zone: eu-west-1a
      containers:
        - image: nginx:latest
          name: nginx
          volumeMounts:
            - name: vol-nginx
              mountPath: /mnt/
      volumes:
        - name: vol-nginx
          persistentVolumeClaim:
            claimName: pvc-nginx
