apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - name: web
    image: web:1.0.0
    volumeMounts:
    - name: database-volume
      mountPath: "/etc/secrets/database"
      readOnly: true
  volumes:
  - name: database-volume
    secret:
      secretName: database
