--- 
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: tls-example-ingress
spec: 
  rules: 
    - host: mydomain.com
      http: 
        paths: 
          - path: / 
            backend: 
              serviceName: my-service
              servicePort: 80
  tls: 
    - hosts: 
        - mydomain.com
      secretName: my-tls-secret
