apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit
  labels:
    app: reddit-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit-clone
  template:
    metadata:
      labels:
        app: reddit-clone
    spec:
      containers:
      - name: reddit-app
        image: ashfaque9x/reddit-clone
        ports:
        - containerPort: 3000
---
