apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
spec:
  containers:
  - name: k8s-demo
    image: wardviaene/k8s-demo
    volumeMounts:
    - mountPath: /myvol
      name: myvolume
    ports:
    - containerPort: 3000
  volumes:
  - name: myvolume
    awsElasticBlockStore:
      volumeID: vol-055681138509322ee  
