apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PVC_1
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteMany
  - ReadOnlyMany
  storageClassName: ""
  selector:
    matchLabels:
      tier: dev
