apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PVC_2
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteMany
  - ReadOnlyMany
  storageClassName: ""
  volumeName: PV
