apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app : nginx
spec:
  containers:
  - image: registry.cloudyuga.guru/library/nginx
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: Directory
