apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx-1.25.3
spec:
  restartPolicy: Never
  containers:
  - name: nginx          
    image: nginx:1.25.3
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  nodeSelector:
    app: "nginx"
