apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
  labels:
    type: gcePD
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4
